### ISSUE TITLE
Getting error while trying to click and open a field which has null value

### ISSUE THREAD

**Issue by sudhakarchola** [MEddarhri/react-ios-time-picker#1]
Example :

import React, { useState } from 'react';
import { TimePicker } from 'react-ios-time-picker';

export default const  MyApp = () => {
   const [value, setValue] = useState(null);

   const onChange = (timeValue) => {
      setValue(timeValue);
   }

   return (
      <div>
         <TimePicker onChange={onChange} value={value} />
      </div>
   );
}

Error:

TimePicker.js:1233 Uncaught TypeError: Cannot read properties of null (reading 'slice')
    at H (TimePicker.js:1233:1)

**Comment by MEddarhri** [comment]
Thank you @sudhakarchola for letting me know, i'm gonna get a look a that very soon.

**Comment by sudhakarchola** [comment]
Thank you for the quick fix. @MEddarhri
