### ISSUE TITLE
pickerDefaultValue

### ISSUE THREAD

**Issue by sufyaniqbaldev** [MEddarhri/react-ios-time-picker#2]
I am trying to set pickerDefaultValue from string state but not working.

  const [time, setTime] = useState(`${moment(new Date()).format('LT')}`)
<TimePicker
        onChange={onChange}
        pickerDefaultValue= {time}
        use12Hours
        className="form-control"
      />

**Comment by MEddarhri** [comment]
Hi @sufyaniqbaldev, could you please provide a sandbox or a full example, thanks.

**Comment by MEddarhri** [comment]
I think the issue is you're using pickerDefaultvalue and value at the same time, when both are present, pickerDefaultValue is ignored, i wish this can help @sufyaniqbaldev.

**Comment by MEddarhri** [comment]
Hi @sufyaniqbaldev, your momentjs format isn't right, use this format :

`
const [time, setTime] = useState(moment(new Date()).format('HH:MM A'))
`

**Comment by sufyaniqbaldev** [comment]
thanks

**Comment by sufyaniqbaldev** [comment]
const [time, setTime] = useState(moment(new Date()).format("HH:MM A"));
 upper code in states section
 

``` < TimePicker
      onChange={onChange}
      pickerDefaultValue={time}
      className="form-control"
      use12Hours```
    />
I am passing time state and still getting an error  


![image](https://user-images.githubusercontent.com/77877844/192808039-837879cb-7e7d-4c79-a1a3-937c29fb6529.png)

**Comment by MEddarhri** [comment]
Hey @sufyaniqbaldev , i tried it and everything is working fine, i hope you figure it out .
